### ISSUE TITLE
Help wanted, using this plugin with CKEditor 4.x version

### ISSUE THREAD

**Issue by anemdhana** [tag1consulting/ckeditor_comment#4]
I am using CKEditor 4.x version and didnt see any toolbar buttons to verify this plugin works for me. Could you help me here.
Do you have time to create webjar to easily inlcude this in my project

**Comment by anemdhana** [comment]
We have the following if evaluated to false, how to force this as 'true'
editor.Comments = new CKEDITOR.Comments(editor);
      if (editor.Comments.enabled) {

**Comment by anemdhana** [comment]
Do you have working example, instructions to add this plugin to my existing CKeditor 4.x ? Pls share.

**Comment by markcarver** [comment]
The instructions for getting the latest code to work are on the README.md page. However, the development of this plugin has been postponed due to this being an internal project. It was originally based on CKE 4.3. Whether or not that works for the latest CKE versions or not, I'm not sure, but it sounds like it doesn't.

I do not have time to hand hold or to restart development on this project.

FWIW, I got the emails for this repo, there was no need to also create an issue issue of another org/repository that has nothing to do with this... o_O
