### ISSUE TITLE
Project continuity

### ISSUE THREAD

**Issue by dariomac** [tag1consulting/ckeditor_comment#6]
We are adding editorial tools to our Drupal backoffice and (by chance) one of our developers found ckeditor_comments on github. Quickly we tested it, with last ckeditor version, and it works like a charm. However, after looking the code a bit closer, we saw that some features doesn't work while other aren't even coded.

So, I'm wondering if there is a more completed version of this module somewhere or you suspended the development of it for some reason (as I suspect). If this is the case (as I suspect), maybe some guidelines about how to end it or any other documentation about how it was initially designed would be fine!

**Comment by markcarver** [comment]
> So, I'm wondering if there is a more completed version of this module somewhere

Nope, this is it.

> you suspended the development of it for some reason

Mainly because this was an internal project originally designed to help with our editorial process for Drupal Watchdog. However, client work continued to take priority and then ultimately the [publication was sold](http://www.drupalwatchdog.com/blog/2016/5/drupal-watchdog-joins-linux-new-media-family).

> maybe some guidelines about how to end it

There really isn't any "guidelines". This was simply a POC more than anything in an attempt to solve a unique issue for us.

IIRC, the majority of the code that was still needed mainly pertained to implementing the BE aspects.

But, to be quite frank, I really don't remember a lot of the internals of the project anymore. If I were to create this from scratch, I'd probably use CKE's widgets and ES6 to simplify a lot of the FE code.
